### ISSUE TITLE
Is the weights of convs reused in the Stage 3 ？

### ISSUE THREAD

**Issue by DehuaTang** [facebookresearch/DepthShrinker#1]
Hi, in the Stage 3,  we just replaced the depthwise conv and pointwise conv with a normal 3x3 convolution, and the weights are not reused, right?  If not reuse the weights, why do we need finetune for the Stage 2 ?

**Comment by tilmto** [comment]
Hi, in the stage 3, the weights are "reused". More specifically, consecutive linear operations (like the dws and pws conv without non-linearity between them) can be merged into another single operation as mathematically formulated in the Sec. 4.4 of our paper. Our current open-sourced code doesn't describe this mathematical process and only provide a simulated one for measuring throughputs.

**Comment by DehuaTang** [comment]
There is no part of your code that "reloads the weights", right? If so, could you please show me.
I can understand the formula you mentioned  in the Sec. 4.4 , but I don't know how to “reloads the weights” specifically

**Comment by tilmto** [comment]
Basically three consecutive linear operations can be merged into one linear operation mathematically thus we define the corresponding merged operation for measuring throughput. For the detailed implementation of weight reloading described in Sec. 4.4, we will consider release it as a tool in the future.

**Comment by Tomingz** [comment]
good work, when the code of Sec.4.4 will be released?

**Comment by DehuaTang** [comment]
Thanks, looking forward to the code of Sec.4.4.
